dependencies:
  build:
    - ruby:2.7.2

build_targets:
  - name: default
    commands:
      - gem build friendly_uuid
      - gem install ./friendly_uuid-*.gem
  - name: release
    commands:
      - gem install bundler
      - bash release.sh

exec:
  environment:

ci:
  builds:
    - name: default
      build_target: default
    - name: release
      build_target: release
      when: tagged IS true
