dependencies:
  build:
    - node:12.19.0
    - ruby:2.7.2

build_targets:
  - name: default
    commands:
      - gem build friendly_uuid
      - gem install ./friendly_uuid-*.gem

exec:
  environment:

ci:
  builds:
    - name: default
      build_target: default
